replicaCount: 1

backend:
  image:
    repository: ghcr.io/noeulnight/kube-visualizer-backend
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 3000
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

visualizer:
  image:
    repository: ghcr.io/noeulnight/kube-visualizer-frontend
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: ""
  tls:
    enabled: false
    secretName: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""
