import {
  NamespaceNode,
  DomainNode,
  NodeNode,
  PodNode,
  ServiceNode,
  IngressNode,
  DeploymentNode,
  ReplicaSetNode,
  DaemonSetNode,
  StatefulSetNode,
  ConfigMapNode,
  SecretNode,
  ServiceAccountNode,
  EndpointSliceNode,
  PersistentVolumeNode,
  PersistentVolumeClaimNode,
} from "./ResourceNodes";

export const nodeTypes = {
  namespace: NamespaceNode,
  domain: DomainNode,
  node: NodeNode,
  pod: PodNode,
  service: ServiceNode,
  ingress: IngressNode,
  deployment: DeploymentNode,
  replicaSet: ReplicaSetNode,
  daemonSet: DaemonSetNode,
  statefulSet: StatefulSetNode,
  configMap: ConfigMapNode,
  secret: SecretNode,
  serviceAccount: ServiceAccountNode,
  endpointSlice: EndpointSliceNode,
  persistentVolume: PersistentVolumeNode,
  persistentVolumeClaim: PersistentVolumeClaimNode,
};
