{{- if .Values.ingress.enabled -}}
{{- $fullName := include "kube-visualizer.fullname" . -}}
{{- $svcPort := .Values.visualizer.service.port -}}
{{- $backendSvcName := printf "%s-backend" $fullName -}}
{{- $backendSvcPort := .Values.backend.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "kube-visualizer.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /events
            pathType: Prefix
            backend:
              service:
                name: {{ $backendSvcName }}
                port:
                  number: {{ $backendSvcPort }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ $backendSvcName }}
                port:
                  number: {{ $backendSvcPort }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-visualizer" $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
